const data = {
    products: [
        {
            name: 'Iphone 12',
            slug: 'iphone-12',
            category:'Mobiles',
            images:'./img/iphone12.png',
            price: 500,
            countInStock: 10,
            brand: 'Apple',
            ratig: 4.5,
            description:'Тут описание карточки',
        },
        {
            name: 'Iphone 13',
            slug: 'iphone-13',
            category :'Mobiles',
            images:'./img/iphone12.png',
            price: 500,
            countInStock: 10,
            brand: 'Apple',
            ratig: 4.5,
            description:'Тут описание карточки',
        },
        {
            name: 'Samsung a50',
            slug: 'samsung-a50',
            category:'Mobiles',
            images:'./img/iphone12.png',
            price: 500,
            countInStock: 10,
            brand: 'Samsung',
            ratig: 4.5,
            description:'Тут описание карточки',
        },
        {
            name: 'Samsung a55',
            slug: 'samsung-a55',
            category:'Mobiles',
            images:'./img/iphone12.png',
            price: 500,
            countInStock: 10,
            brand: 'Samsung',
            ratig: 4.5,
            description:'Тут описание карточки',
        },
        {
            name: 'Samsung a56',
            slug: 'samsung-a56',
            category:'Mobiles',
            images:'./img/iphone12.png',
            price: 500,
            countInStock: 10,
            brand: 'Samsung',
            ratig: 4.5,
            description:'Тут описание карточки',
        },
        {
            name: 'Samsung a57',
            slug: 'samsung-a57',
            category:'Mobiles',
            images:'./img/iphone12.png',
            price: 500,
            countInStock: 10,
            brand: 'Samsung',
            ratig: 4.5,
            description:'Тут описание карточки',
        },
        {
            name: 'Samsung a58',
            slug: 'samsung-a58',
            category:'Mobiles',
            images:'./img/iphone12.png',
            price: 500,
            countInStock: 10,
            brand: 'Samsung',
            ratig: 4.5,
            description:'Тут описание карточки',
        },
    ]
}
export default data;